plugins {
    id "java"
    id "application"
}

repositories {
    mavenCentral()
}

dependencies {
    implementation "org.apache.logging.log4j:log4j-core:2.14.1"
    implementation "com.fasterxml.jackson.core:jackson-databind:2.9.9"
}

application {
    mainClass = "com.secureflow.App"
}

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}
