name: SecureFlow CI

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read
  security-events: write
  actions: read

jobs:
  secureflow:
    uses: thebinario/secureflow-devsecops/.github/workflows/secure-ci.yml@main
    with:
      enable_sast: true
      enable_secrets: true
      enable_dependencies: false
      enable_container: false
      enable_iac: false
